module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V3.Types
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V3.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V3.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V3.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    MsgOldValueIgnored


toBackend : Evergreen.V3.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V3.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V3.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_HasPressedSubmit : Evergreen.V3.Types.HasPressedSubmit -> Evergreen.V4.Types.HasPressedSubmit
migrate_Types_HasPressedSubmit old =
    case old of
        Evergreen.V3.Types.HasPressedSubmit ->
            Evergreen.V4.Types.HasPressedSubmit

        Evergreen.V3.Types.HasNotPressedSubmit ->
            Evergreen.V4.Types.HasNotPressedSubmit


migrate_Types_SubmitStatus : Evergreen.V3.Types.SubmitStatus -> Evergreen.V4.Types.SubmitStatus
migrate_Types_SubmitStatus old =
    case old of
        Evergreen.V3.Types.NotSubmitted p0 p1 ->
            Evergreen.V4.Types.NotSubmitted (p0 |> migrate_Types_HasPressedSubmit) p1

        Evergreen.V3.Types.Submitting ->
            Evergreen.V4.Types.Submitting
